### ISSUE TITLE
how to use the model after train?

### ISSUE THREAD

**Issue by sanersbug** [icoz69/CaNet#12]
I find that the forward need 4 parameter ,' query_rgb','support_rgb','support_mask','history_mask',
what's mean of the 'support_rgb','support_mask'? how can i get it , if it is any image with label?

when i use the network to predict a image , how modify the code ?

Thanks a lot!

**Comment by MSiam** [comment]
Support set: is the training set with few labelled examples. So you want to provide support RGB image and support 0/1 segmentation mask for the new class outside the 15 classes it was meta-trained on. query is the image you want to segment with an object from the new class. history_mask u can initialize to zeros in the beginning.

**Comment by sanersbug** [comment]
Thank you very much! @MSiam 
And would you mind give some advice about the predict period , how to modify the code to complete the inference.
