### ISSUE TITLE
Data question

### ISSUE THREAD

**Issue by Hevans123** [icoz69/CaNet#18]
Hi,  @icoz69 . It seems that you exclude some data sample of PASCAL-5i in your experiment. 
In the  directory 'Binary_map_aug/train/1',  it contains 586 pictures (***.png).
But in the 'Binary_map_aug/train/1.txt', it only contains 528 file names.
Can you please correct me if there is something I misunderstood in your data setting?

**Comment by icoz69** [comment]
hi, 
yes, you are right. we follow the original data preprocessing operations in the source code of OSLSM (shaban et al.), which filters some small objects. Actually, we simply run their code and saved the filtered data index into the text file, while the folders you mentioned contain both filtered and unfiltered data.  
You can find the filtering operations in the original OSLSM code [here](https://github.com/lzzcd001/OSLSM/blob/master/OSLSM/code/ss_datalayer.py) .
