### ISSUE TITLE
Some setting questions

### ISSUE THREAD

**Issue by lxtGH** [icoz69/CaNet#19]
Hi! @icoz69 Thanks for your open sourced code. It is a very nice work ! Could you provide the detailed setting on COCO subset ?

**Comment by lxtGH** [comment]
Also. why you fix the imagenet pretrained weights during the training ??

**Comment by terryphillip87** [comment]
hello. as the project here is modified for easy reading, the coco loader may not compatible directly with the  API in this repo. I will modify the code the upload them here in the future. Before that
you can  drop me an email (in the paper), such that i can send the raw coco data and loader to you. 
as to the imagenet pre-trained weights, i find it helpful to fix it such that the network focus on learning the reasoning part not obect features. anyway, it yields better results.

**Comment by icoz69** [comment]
hello. as the project here is modified for easy reading, the coco loader may not compatible directly with the API in this repo. I will modify the code the upload them here in the future. Before that
you can drop me an email (in the paper), such that i can send the raw coco data and loader to you.
as to the imagenet pre-trained weights, i find it helpful to fix it such that the network focus on learning the reasoning part not object features. anyway, it yields better results.

**Comment by lxtGH** [comment]
Hi thanks for your reply.
