### ISSUE TITLE
code release date

### ISSUE THREAD

**Issue by kate-sann5100** [icoz69/CaNet#3]
The cvpr conference has already finished, may I know when the code will be released please?

**Comment by MSiam** [comment]
Yeah I am also interested in the code so I can compare and confirm my results with my current work. Thanks

**Comment by henrywfyeung** [comment]
+1 Would be glad if you can release the code

**Comment by amiltonwong** [comment]
Hi, authors,

When would you release the code?

**Comment by GrimReaperSam** [comment]
+1 Would like to see the code and a demo on how to run it
