### ISSUE TITLE
Process Data Error

### ISSUE THREAD

**Issue by MSiam** [icoz69/CaNet#5]
Hello

The file for Binary_amp_aug.zip does not extract properly is there an issue with it?

Thanks

**Comment by MSiam** [comment]
I actually still have the problem, the file for Binary_map_aug.zip I am not able to extract?
Would be great if you can upload the corrected one. thanks

**Comment by icoz69** [comment]
hi i have tried many times on different computers. maybe you can try a different software?

**Comment by MSiam** [comment]
No worries sorry I am able to extract it now thanks. I am wondering if you have as well the exact 1000 sampled pairs from OSLSM? Cause I found that using different random pairs does affect the accuracies and I had to save the pairs paths as is from OSLSM loader to ensure the correctness of my experiments. 
The pre-processed data doesn't seem to have the pairs itself. It would be great if you can only provide the loader even just want to ensure the consistency of my experiments as I want t compare with your method. Greatly appreciate your response thanks.
